### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#158]
Cody should have a way for repository owners to configure how Cody behaves. The general pattern for this in GitHub apps is to use a config file stored in the repo.

[Probot's recommendation](https://probot.github.io/docs/best-practices/#configuration) is to use a YAML file stored in the `.github` directory. That's fine for GitHub projects, but it might be better to remain agnostic to the hosting provider? I don't know if I would ever be able to reasonably support other hosts like BitBucket since I just don't use them.

Format is up for bikeshedding. YAML is pretty universal in the Ruby world, but JSON is also pretty ubiquitous. TOML is also gaining popularity. My main concern here is how easy it is to edit the format manually and not make mistakes. In that regard, YAML and TOML clearly win over JSON, which is very tedious to write manually.

Regardless the file format I would want to use JSON Schema to validate the resulting Hash.

**Comment by aergonaut** [comment]
## YAML format

```yaml
schemaVersion: 1
minimumReviewers: 1
rules:
  secondLevel:
    name: Second Level Review
    match: true
    reviewer: @coupa/system-reviewers
  migrations:
    name: Migrations Review
    match:
      path:
        - db/migrate/*
    reviewer: @coupa/migrations-reviewers
```

**Comment by aergonaut** [comment]
## JSON format

```json
{
  "schemaVersion": 1,
  "minimumReviewers": 1,
  "rules": {
    "secondLevel": {
      "name": "Second Level Review",
      "match": true,
      "reviewer": "@coupa/system-reviewers"
    },
    "migrations": {
      "name": "Migrations Review",
      "match": {
        "path": [
          "db/migrate/*"
        ]
      },
      "reivewer": "@coupa/migrations-reviewers"
    }
  }
}
```

**Comment by aergonaut** [comment]
## TOML format

```toml
schemaVersion = 1

minimumReviewers = 1

[rules.secondLevel]
name = "Second Level Review"
match = true
reviewer = "@coupa/system-reviewers"

[rules.migrations]
name = "Migrations Review"
match = { path: ["db/migrate/*"] }
reviewer = "@coupa/migrations-reviewers"
```
