### ISSUE TITLE
Rule to add reviewer based on PR author

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#82]
Conditions:
- If the author is part of a specific team
- If the author is a specific GitHub user

**Comment by aergonaut** [comment]
```yaml
rules:
  - name: Author Rule
    reviewer: someone
    match:
      author: individual-user # or organization/team
```
